### ISSUE TITLE
运行有报错

### ISSUE THREAD

**Issue by GstXu** [chaxiu/ComposeInAction#1]
您好，这个项目运行了第一个报错是application问题，
第二个是NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference ，感觉后面可能还有报错，你那边能运行正常吗

**Comment by chaxiu** [comment]
漏了一个提交，application没放进 XML，你重新试试就行了。
